name: Deploy Frontend to S3 and CloudFront

on:
  push:
    branches: [master, main]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  NODE_VERSION: '18'
  # AWS Resource Values from Terraform Output
  S3_BUCKET_NAME: mediamint-prod-frontend-fb3e517c
  CLOUDFRONT_DISTRIBUTION_ID: ER9BLNAJA670K
  CLOUDFRONT_DOMAIN_NAME: d3mdc4iuhybuoe.cloudfront.net
  VITE_BACKEND_URL: https://mediamint-prod-1184789238.us-east-1.elb.amazonaws.com

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          VITE_BACKEND_URL: ${{ env.VITE_BACKEND_URL }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync dist/ s3://${{ env.S3_BUCKET_NAME }} --delete --exact-timestamps
        
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"

      - name: Deployment Summary
        run: |
          echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "Frontend successfully deployed to S3" >> $GITHUB_STEP_SUMMARY
          echo "CloudFront cache invalidated" >> $GITHUB_STEP_SUMMARY
          echo "CloudFront URL: https://${{ env.CLOUDFRONT_DOMAIN_NAME }}" >> $GITHUB_STEP_SUMMARY
